version: '1'
services:
  api:
    build: ./ingreso
    container_name: back-end
    ports:
      - "8087:8080"
    environment:
      - SPRING.PROFILES.ACTIVE=default, in-memory
  web:
    build: ./craftech
    container_name: front-end
    ports:
      - "3030:3000"